<center>
    <img src="https://gitlab.com/ibm/skills-network/courses/placeholder101/-/raw/master/labs/module%201/images/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# Peer Review Assignment - Data Engineer - ETL - Jeong Hoon Kim / 02.28.22

Estimated time needed: **20** minutes

## Objectives

In this final part you will:

*   Run the ETL process
*   Extract bank and market cap data from the JSON file `bank_market_cap.json`
*   Transform the market cap currency using the exchange rate data
*   Load the transformed data into a seperate CSV

For this lab, we are going to be using Python and several Python libraries. Some of these libraries might be installed in your lab environment or in SN Labs. Others may need to be installed by you. The cells below will install these libraries when executed.

In [51]:
#!pip install glob
#!pip install pandas
#!pip install requests
#!pip install datetime

## Imports

Import any additional libraries you may need here.

In [52]:
import glob
import pandas as pd
from datetime import datetime

As the exchange rate fluctuates, we will download the same dataset to make marking simpler. This will be in the same format as the dataset you used in the last section

In [53]:
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_1.json
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_2.json
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Final%20Assignment/exchange_rates.csv

--2022-02-28 20:15:29--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_1.json
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 198.23.119.245
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|198.23.119.245|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2815 (2.7K) [application/json]
Saving to: ‘bank_market_cap_1.json.3’

bank_market_cap_1.j 100%[===================>]   2.75K  --.-KB/s    in 0s

2022-02-28 20:15:29 (85.3 MB/s) - ‘bank_market_cap_1.json.3’ saved [2815/2815]

--2022-02-28 20:15:30--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_2.json
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 198.23.119.245
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|198.23.119.245|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1429 (1.4K) [application/json]
Saving to: ‘bank_market_cap_2.json.3’

bank_market_cap_2.j 100%[===================>]   1.40K  --.-KB/s    in 0s

2022-02-28 20:15:30 (44.1 MB/s) - ‘bank_market_cap_2.json.3’ saved [1429/1429]

--2022-02-28 20:15:31--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Final%20Assignment/exchange_rates.csv
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 198.23.119.245
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|198.23.119.245|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 590 [text/csv]
Saving to: ‘exchange_rates.csv.3’

exchange_rates.csv. 100%[===================>]     590  --.-KB/s    in 0s

2022-02-28 20:15:31 (18.2 MB/s) - ‘exchange_rates.csv.3’ saved [590/590]

## Extract

### JSON Extract Function

This function will extract JSON files.

In [54]:
def extract_from_json(file_to_process):
    dataframe = pd.read_json(file_to_process)
    return dataframe

## Extract Function

Define the extract function that finds JSON file `bank_market_cap_1.json` and calls the function created above to extract data from them. Store the data in a `pandas` dataframe. Use the following list for the columns.

In [55]:
columns=['Name','Market Cap (US$ Billion)']

In [56]:
def extract():
    extracted_data = pd.DataFrame(columns=['Name','Market Cap (US$ Billion)'])
    
    for jsonfile in glob.glob("bank_market_cap_1.json"):
        extracted_data = extracted_data.append(extract_from_json(jsonfile), ignore_index=True)
        
    return extracted_data

<b>Question 1</b> Load the file <code>exchange_rates.csv</code> as a dataframe and find the exchange rate for British pounds with the symbol <code>GBP</code>, store it in the variable  <code>exchange_rate</code>, you will be asked for the number. Hint: set the parameter  <code>index_col</code> to 0.

In [57]:
# Write your code here
def extract_from_csv(file_to_process):
    dataframe = pd.read_csv(file_to_process)
    return dataframe

exchange_rates_csv = extract_from_csv("exchange_rates.csv")
exchange_rates_csv = exchange_rates_csv.rename(columns={'Unnamed: 0': 'Currency'})
exchange_rate = exchange_rates_csv[exchange_rates_csv['Currency'] == 'GBP']
exchange_rate

  Currency     Rates
9      GBP  0.732398

## Transform

Using <code>exchange_rate</code> and the `exchange_rates.csv` file find the exchange rate of USD to GBP. Write a transform function that

1.  Changes the `Market Cap (US$ Billion)` column from USD to GBP
2.  Rounds the Market Cap (US$ Billion)\` column to 3 decimal places
3.  Rename `Market Cap (US$ Billion)` to `Market Cap (GBP$ Billion)`

In [67]:
def transform(data):
        data['Market Cap (US$ Billion)'] = round(data['Market Cap (US$ Billion)'] * 0.732398, 3)
        data = data.rename(columns = {"Market Cap (US$ Billion)": "Market Cap (GBP$ Billion)"})
        return data

## Load

Create a function that takes a dataframe and load it to a csv named `bank_market_cap_gbp.csv`. Make sure to set `index` to `False`.

In [68]:
targetfile = "bank_market_cap_gbp.csv"

def load(targetfile, data_to_load):
    data_to_load.to_csv(targetfile)

## Logging Function

Write the logging function <code>log</code> to log your data:

In [69]:
def log(message):
    timestamp_format = '%H:%M:%S-%h-%d-%Y'
    now = datetime.now() 
    timestamp = now.strftime(timestamp_format)
    with open("dealership_logfile.txt","a") as f:
        f.write(timestamp + ',' + message + '\n')

## Running the ETL Process

Log the process accordingly using the following <code>"ETL Job Started"</code> and <code>"Extract phase Started"</code>

In [70]:
# Write your code here
log("ETL Job Started")
log("Extract phase Started")

### Extract

<code>Question 2</code> Use the function <code>extract</code>, and print the first 5 rows, take a screen shot:

In [71]:
# Call the function here
extracted_data = extract()
# Print the rows here
extracted_data.head()

                                      Name  Market Cap (US$ Billion)
0                           JPMorgan Chase                   390.934
1  Industrial and Commercial Bank of China                   345.214
2                          Bank of America                   325.331
3                              Wells Fargo                   308.013
4                  China Construction Bank                   257.399

Log the data as <code>"Extract phase Ended"</code>

In [72]:
# Write your code here
log("Extract phase Ended")

### Transform

Log the following  <code>"Transform phase Started"</code>

In [73]:
# Write your code here
log("Transform phase Started")

<code>Question 3</code> Use the function <code>transform</code> and print the first 5 rows of the output, take a screen shot:

In [74]:
# Call the function here
transformed_data = transform(extracted_data)
# Print the first 5 rows here
transformed_data.head()

                                      Name  Market Cap (GBP$ Billion)
0                           JPMorgan Chase                    286.319
1  Industrial and Commercial Bank of China                    252.834
2                          Bank of America                    238.272
3                              Wells Fargo                    225.588
4                  China Construction Bank                    188.519

Log your data <code>"Transform phase Ended"</code>

In [75]:
# Write your code here
log("Transform phase Ended")

### Load

Log the following `"Load phase Started"`.

In [76]:
# Write your code here
log("Load phase Started")

Call the load function

In [77]:
# Write your code here
load(targetfile, transformed_data)

Log the following `"Load phase Ended"`.

In [78]:
# Write your code here
log("Load phase Ended")

## Authors

Ramesh Sannareddy, Joseph Santrcangelo and Azim Hirjani

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-11-25        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork23455645-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).